(clientes = [{name: "Juan Perez" gender: "Male" age: 32 discount: false}
             {name: "Camila Rodriguz" gender: "Female"  age: 21 discount:  false}
             {name: "Viktor Bond" gender: "Male" age: 16 discount: false}
             {name: "Mat Bilan" gender: "Male" age: 54 discount: false}
             {name: "Juanita Morales" gender: "Female" age: 18 discount: false}
             {name: "Guadalupe Builes" gender: "Female" age: 34 discount: false}
             {name: "Felipe Bueno" gender: "Male" age: 44 discount: false }
             {name: "Diomédez Dias" gender: "Male" age: 67 discount: false}
             {name: "Cris Lara" gender: "Female" age: 12 discount: false}
             {name: "Camilo Jimenez" gender: "Male" age: 26 discount: false}
             {name: "Rogelio Buendía" gender: "Male" age: 33 discount: false}
             {name: "Florinda Mesa" gender: "Female" age: 27 discount: false}
             {name: "Alejandra Mesa" gender: "Female" age: 67 discount: false} 
             {name: "Ana Jaramillo" gender: "Female" age: 56 discount: false} 
             {name: "Luis Gomez" gender: "Male" age: 35 discount: false} 
             {name: "Leo Ruiz" gender: "Male" age: 44  discount: false} 
             {name: "Gali Galeano" gender: "Male" age: 30 discount: false} 
             {name: "Daniela Romo" gender: "Female" age: 28 discount: false} 
             {name: "Carlos Carrera" gender: "Male" age: 10 discount: false} 
             {name: "James Bond" gender: "Male" age: 74 discount: false} 
             {name: "Barbara Blade" gender: "Female"  age: 24 discount: false}
             {name: "Caro Cardona" gender: "Female"  age: 23 discount: false} 
             {name: "Fernando Rueda" gender: "Male" age: 45 discount: false} 
             {name: "Nelson Madela" gender: "Male" age: 28 discount: false} 
             {name: "Indira Gandi" gender: "Female"  age: 49 discount: false} 
             {name: "Fede Rico" gender: "Male" age: 34 discount: false}
             {name: "Constanza Camelo" gender: "Female" age: 57 discount: false}
             {name: "Marcela Mar" gender: "Female"  age: 31 discount: false}
             {name: "Roberto Gomez" gender: "Male" age: 29 discount: false}
             {name: "Catalina Rivas" gender:  "Female" age: 32 discount: false}])
